# Generated by Django 4.1.5 on 2023-04-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='event_id',
            field=models.IntegerField(null=True),
        ),
    ]
