# Generated by Django 4.1.5 on 2023-04-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
        ('event', '0002_event_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_participants',
            field=models.ManyToManyField(null=True, to='users.profile'),
        ),
    ]
