# Generated by Django 4.1.5 on 2023-04-04 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
        ('event', '0006_alter_event_event_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_participants',
        ),
        migrations.AddField(
            model_name='event',
            name='event_participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_events', to='users.profile'),
        ),
    ]
