# Generated by Django 4.1.5 on 2023-04-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_event_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_url',
            field=models.URLField(default='http://127.0.0.1:8000'),
        ),
    ]
